/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoader: typeof import('./src/components/common/AppLoader.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    JsonEditor: typeof import('./src/components/common/JsonEditor.vue')['default']
    LogEntry: typeof import('./src/components/common/LogViewer/LogEntry.vue')['default']
    LogViewer: typeof import('./src/components/common/LogViewer/index.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
  }
}
